name: 'oxs-check-updates'
description: 'Checks the updated files in a PR and give the folders from the files back.'

branding:
  icon: log-in
  color: 'blue'

inputs: 
  searchFolder:
    description: 'The folder in which the updated files will be checked.'
    required: true

outputs:
  folders:
    description: 'The folders in which the files was changed.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files in the selected folder
      id: changed-files-folder
      uses: tj-actions/changed-files@v45
      with:
        files: ${{ inputs.searchFolder }}/**

    - name: Extract changed folders and store in env variable
      shell: bash
      run: |
        FOLDERS=()
        IFS=$'\n'
        declare -A folder_files

        for file in $(echo "${{ steps.changed-files-folder.outputs.all_changed_files }}" | tr ' ' '\n'); do
          folder=$(echo "$file" | cut -d'/' -f2)  # Get the immediate subfolder under the input folder
          filename=$(basename "$file")

          # Accumulate filenames per folder
          folder_files["$folder"]+="$filename "
        done

        for folder in "${!folder_files[@]}"; do
          files=(${folder_files[$folder]})
          # If only one file and it's manifest.json, skip
          if [[ ${#files[@]} -eq 1 && "${files[0]}" == "manifest.json" ]]; then
            continue
          fi
          FOLDERS+=("$folder")
        done

        echo "folders=${FOLDERS[@]}" >> $GITHUB_ENV
