name: 'oxs-check-updates'
description: 'Checks the updated files in a PR and give the folders from the files back.'

branding:
  icon: log-in
  color: 'blue'

inputs: 
  searchFolder:
    description: 'The folder in which the updated files will be checked.'
    required: true

outputs:
  folders:
    description: 'The folders in which the files was changed.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files in the selected folder
      id: changed-files-folder
      uses: tj-actions/changed-files@v45
      with:
        files: ${{ inputs.searchFolder }}/**

    - name: Extract changed folders and store in env variable
      shell: bash
      run: |
        declare -A folder_files
        FOLDERS=()
    
        while IFS= read -r file; do
          # Remove the searchFolder prefix
          relative="${file#${{ inputs.searchFolder }}/}"
    
          # Get the first directory under searchFolder
          folder="${relative%%/*}"
    
          filename="$(basename "$file")"
    
          folder_files["$folder"]+="$filename"$'\n'
        done <<< "${{ steps.changed-files-folder.outputs.all_changed_files }}"
    
        for folder in "${!folder_files[@]}"; do
          mapfile -t files <<< "${folder_files[$folder]}"
    
          # Skip folder if ONLY manifest.json was changed
          if [[ ${#files[@]} -eq 1 && "${files[0]}" == "manifest.json" ]]; then
            continue
          fi
    
          FOLDERS+=("$folder")
        done
    
        echo "folders=${FOLDERS[*]}" >> "$GITHUB_ENV"
